### ISSUE TITLE
Language issues (Nana <3)

### ISSUE THREAD

**Issue by elifoster** [FTB-Gamepedia/FTB-Wiki-Issue-Tracker#16] opened 2015-01-07 00:57 UTC
When not signed in and visiting the site it will appear in different languages, different every time you reload the page. When you are signed in it's fine. This does not affect the whole page just the nav area

This was first reported on November 28, and has been reported several times by Nana, and other random people in the IRC channel.

**Comment by Telshin** [comment] 2015-01-07 22:57
When you refer to nav, are you referring to the sidebar? If not, does anyone have a screenshot of the affected nav piece?

**Comment by Farrser** [comment] 2015-01-08 00:09
I cannot reproduce at this time as the language swaps between seemingly randomly and its currently in english. The affected area is the top nav (discussion, page share) and the side nav but not the page content.

**Comment by elifoster** [comment] 2015-01-08 00:37
My guess is that the page content would be affected if there was a translation available in that language for that page?

**Comment by Telshin** [comment] 2015-01-09 23:09
We've put in a setting to stop this from happening due to anonymous traffic caching those language settings.

**Comment by Telshin** [comment] 2015-01-19 17:51
Any update @captainnana?

**Comment by Farrser** [comment] 2015-01-20 22:28
Not having the issue atm but I am on a different network so I guess we can assume this is fixed unless it happens again

**Comment by Telshin** [comment] 2015-02-02 19:08
Has this happened again?

**Comment by Telshin** [comment] 2015-05-05 19:14
Bump!

**Comment by Farrser** [comment] 2015-05-06 15:23
I've had no further reports and can no longer produce error so fixed as far as I know

**Comment by Telshin** [comment] 2015-05-06 15:42
Excellent. We can close this out then!

**Closed as completed** 2015-05-06 16:45 UTC
Labels: bug
